// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqreoU9-SuLDAIXFSTeaO9goLM1IN6uY8',
    appId: '1:363089986677:web:cf4b13c784f43c6688a43c',
    messagingSenderId: '363089986677',
    projectId: 'yuutebrok-e03d0',
    authDomain: 'yuutebrok-e03d0.firebaseapp.com',
    storageBucket: 'yuutebrok-e03d0.appspot.com',
    measurementId: 'G-N33NN3S993',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvLxClg1WrQyYgN0jMQSJvkQArQ1wKReM',
    appId: '1:363089986677:android:e8673735a76612d488a43c',
    messagingSenderId: '363089986677',
    projectId: 'yuutebrok-e03d0',
    storageBucket: 'yuutebrok-e03d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGj0Ub0BaF7LHgNSIdwaqW-U-yofuRI0M',
    appId: '1:363089986677:ios:261b3e917a07ce8188a43c',
    messagingSenderId: '363089986677',
    projectId: 'yuutebrok-e03d0',
    storageBucket: 'yuutebrok-e03d0.appspot.com',
    iosBundleId: 'com.example.yuutAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGj0Ub0BaF7LHgNSIdwaqW-U-yofuRI0M',
    appId: '1:363089986677:ios:261b3e917a07ce8188a43c',
    messagingSenderId: '363089986677',
    projectId: 'yuutebrok-e03d0',
    storageBucket: 'yuutebrok-e03d0.appspot.com',
    iosBundleId: 'com.example.yuutAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqreoU9-SuLDAIXFSTeaO9goLM1IN6uY8',
    appId: '1:363089986677:web:775de180a17bfe3a88a43c',
    messagingSenderId: '363089986677',
    projectId: 'yuutebrok-e03d0',
    authDomain: 'yuutebrok-e03d0.firebaseapp.com',
    storageBucket: 'yuutebrok-e03d0.appspot.com',
    measurementId: 'G-966FJB9Q7R',
  );
}
